


#change class of columns in data frames
lfdn<-as.numeric(as.character(personal_info$lfdn))
APdef<-as.numeric(as.character(APdef))
AP_gen<-as.numeric(as.character(AP_questions$AP_gen))
Syn_gen<-as.numeric(as.character(AP_questions$Syn_gen))
AQ_Score<-as.numeric(as.character(AQ_Score))
EQ_Score<-as.numeric(as.character(EQ_Score))
SQ_Score<-as.numeric(as.character(SQ_Score))
AP_sums<-as.numeric(as.character(AP_sums))
semerror<-as.numeric(as.character(semerror))
AQ_AD_Score<-as.numeric(as.character(AQ_AD_Score))
AQ_IM_Score<-as.numeric(as.character(AQ_IM_Score))
AQ_SK_Score<-as.numeric(as.character(AQ_SK_Score))
AQ_SW_Score<-as.numeric(as.character(AQ_SW_Score))
AQ_CO_Score<-as.numeric(as.character(AQ_CO_Score))
begin_instr<-as.numeric(as.character(exp_mus$begin_instr))
main_years<-as.numeric(as.character(music_experience$main_years))
second_years<-as.numeric(as.character(music_experience$second_years))
MSI_Score<-as.numeric(as.character(MSI_Score))
MSI_F1_Score<-as.numeric(as.character(MSI_F1_Score))
MSI_F2_Score<-as.numeric(as.character(MSI_F2_Score))
MSI_F3_Score<-as.numeric(as.character(MSI_F3_Score))
MSI_F4_Score<-as.numeric(as.character(MSI_F4_Score))
MSI_F5_Score<-as.numeric(as.character(MSI_F5_Score))
MSI_FG_Score<-as.numeric(as.character(MSI_FG_Score))
GUF_ASV_Score<-as.numeric(as.character(GUF_ASV_Score))
GUF_ERG_Score<-as.numeric(as.character(GUF_ERG_Score))
GUF_KRH_Score<-as.numeric(as.character(GUF_KRH_Score))
GUF_Score<-as.numeric(as.character(GUF_Score))
musical_situation<-as.numeric(as.character(musical_situation))
psy<-as.numeric(as.character(psy))